### ISSUE TITLE
rub Terminal error when re/moving images

### ISSUE THREAD

**Issue by guywillis** [oliverfoster/adapt-buildkit-rub#1]
When moving or removing images using SmartSVN with a rub dev server (./rub -sd) command active I receive the following error in the rub-check.log file:

> Tue Jul 28 2015 16:11:53 GMT+0100 (BST)<
> p101 - TechSpec: Failed [Error: ENOENT, no such file or directory '/Users/guy.willis/Documents/Projects/ken15089-BritishGypsum/dev/builds/p101/course/en/images/play_icon.png'] course/en/images/play_icon.png

In the above instance I moved the play_icon.png to another folder within the /images folder.

The error was resolved if I cancelled my current command and restarted the server.

**Comment by oliverfoster** [comment]
hopefully fixed in v0.0.53

**Comment by oliverfoster** [comment]
@guywillis can you verify and close this issue please?

**Comment by guywillis** [comment]
Works like a charm. 

Fixed and closed.
