### ISSUE TITLE
Add an Image in the theme's assets directory not added to the course when server is running and watching

### ISSUE THREAD

**Issue by samumist** [oliverfoster/adapt-buildkit-rub#13]
When I add an background image to the theme's assets directory `theme/adapt-contrib-vanilla/assets/` while the server is running and being watched with `./rub -s`. The command-line message reported that the image was added, but it actually didn't. 

When I stop the server and build the course again with `./rub -b`, then the image is indeed added to the `builds/p101/adapt/css/assets/` directory.

and there's nothing in the `rub-check.log` file.

Multiple courses and rub version 0.0.50.

**Comment by oliverfoster** [comment]
hopefully fixed in v0.0.53

**Comment by samumist** [comment]
Just to confirm it is fixed with the new version. 
Many thanks.
