### ISSUE TITLE
Multiple rub courses active

### ISSUE THREAD

**Issue by guywillis** [oliverfoster/adapt-buildkit-rub#14]
When a rub server is active on a course and I try to start a new rub server on a different course, I receive the following error:

> events.js:72
>         throw er; // Unhandled 'error' event
>               ^
> Error: listen EADDRINUSE
>     at errnoException (net.js:905:11)
>     at Server._listen2 (net.js:1043:14)
>     at listen (net.js:1065:10)
>     at Server.listen (net.js:1139:5)
>     at Object.module.exports.start (/Users/guy.willis/Documents/Projects/adapt-kineo-theme/dev/buildkit/libraries/server.js:35:33)
>     at EventEmitter.startServer (/Users/guy.willis/Documents/Projects/adapt-kineo-theme/dev/buildkit/libraries/runner.js:480:17)
>     at EventEmitter._.extend.defer (/Users/guy.willis/Documents/Projects/adapt-kineo-theme/dev/buildkit/libraries/taskqueue.js:131:13)
>     at EventEmitter._.extend.thenWatchForChanges (/Users/guy.willis/Documents/Projects/adapt-kineo-theme/dev/buildkit/libraries/runner.js:475:13)
>     at EventEmitter.<anonymous> (/Users/guy.willis/Documents/Projects/adapt-kineo-theme/dev/buildkit/libraries/runner.js:80:11)
>     at EventEmitter.<anonymous> (/Users/guy.willis/Documents/Projects/adapt-kineo-theme/dev/buildkit/libraries/taskqueue.js:128:14)

**Comment by moloko** [comment]
does this still occur if you set a different port for the new server using the --port option?

**Comment by oliverfoster** [comment]
It shouldn't, but I'd like to automate it

**Comment by oliverfoster** [comment]
done - yet to push

**Comment by oliverfoster** [comment]
pushed
