### ISSUE TITLE
Video (Media component) cannot seek forward or backward while served with "rub -s"

### ISSUE THREAD

**Issue by samumist** [oliverfoster/adapt-buildkit-rub#16]
Video via the contrib-media component cannot be seek backward or forward when served with `rub -s`. When clicking the mouse on the seekbar forward or backward, the video doesn't play from clicking point. Instead, it goes back to the beginning of the video.

The same code built with Grunt doesn't have the problem. 

With some further test, I found that this has nothing to do with the `rub -b` but `rub -s`. 

The code built with `rub -b` but served with `rub -s` is having the above mentioned problem. The same code built with `rub -b` but served with `grunt server` seeks backward and forward correctly.

Same built served from a web server (apache) also worked fine.

**Comment by moloko** [comment]
Were you using Chrome by any chance? I think I'm getting a similar issue - as well as getting 'Error loading this resource' on the media component in IE9 - all works fine when using browser-sync or WAMP server

**Comment by samumist** [comment]
Yes, I'm using Chrome.

**Comment by chucklorenz** [comment]
I receive the 'Error loading this resource' using the rub server and viewing in Chrome (Mac). The error is not raised when the course is viewed from Totara.

**Comment by oliverfoster** [comment]
fix pending testing in branch "develop"

https://github.com/cgkineo/adapt-buildkit-rub/tree/develop

**Comment by moloko** [comment]
@oliverfoster happy to help test this if you can bash out some installation instructions

**Comment by oliverfoster** [comment]
Make sure you've got [node LTS](https://nodejs.org/en/download/) (v4.2.4) as this is using ES6 stuffs

Update adapt-buildkits:

```
npm install -g adapt-buildkits
```

Pick a test course to run the new buildkit in:

```
 adapt-buildkit install rub-develop 
```

**Comment by oliverfoster** [comment]
@moloko ^

**Comment by oliverfoster** [comment]
seems not to work in ff on linux.
works in chrome on linux and chrome on windows.

**Comment by moloko** [comment]
sweet, I'll give it a test in the project I'm working on

**Comment by moloko** [comment]
Unfortunately I wasn't able to replicate the issue in Chrome on Windows before upgrading, so I can't say whether it fixed it for this or not.

I could, however, replicate the 'error loading resource' error in IE9 - which is still present.

**Comment by oliverfoster** [comment]
fixed by using grunt serve-static library. should work exactly the same serving videos as does grunt

rub-develop 0.1.4

**Comment by moloko** [comment]
'error loading resource' error in IE9 now gone for me

@samumist & @chucklorenz could you test in Chrome?

**Comment by samumist** [comment]
I can confirm the new `develop-rub` does fix the problems:
1) video loading problem;
2) fast-forward and backward seeking.

*\* Test Environment**
**OS**: MAC OSX 10.11.2
**Browser**: Chrome, Safari, Firefox (all latest)
**Component**: contribMedia and nativeMedia

Thanks very much.

p.s. I haven't noticed any CPU overuse with the new `develop-rub`, less than 20% from the activity monitor.

**Comment by oliverfoster** [comment]
Cool :)
