### ISSUE TITLE
rub -- tracking commands not working with multiple modules

### ISSUE THREAD

**Issue by simondate** [oliverfoster/adapt-buildkit-rub#19]
When you run: rub --trackingreset , delete or insert in a course with multiple modules it does not work. Have to enter the module in manually. e.g:  rub --trackingreset m05

**Comment by oliverfoster** [comment]
please test using develop branch as per [instructions](https://github.com/cgkineo/adapt-buildkit-rub/issues/16#issuecomment-171721999)

good as of rub-develop 0.1.4

**Comment by samumist** [comment]
Confirm this new `develop-rub` has solved the problem. All --trackinginsert, delete, reset working as expected, and doesn't have to manually type in the course name.
