### ISSUE TITLE
screenSize object in course.json

### ISSUE THREAD

**Issue by tomgreenfield** [oliverfoster/adapt-buildkit-rub#20]
The `screenSize` object in course.json seems to change position in the file for every commit. Is Rub causing this and, if so, can it be prevented?

**Comment by samumist** [comment]
I've had the same issue with the screenSize being inserted to the `course.json` file. It's not a big problem but a bit annoying.

**Comment by oliverfoster** [comment]
have moved to come out where it should in config.json
