### ISSUE TITLE
improvements to README

### ISSUE THREAD

**Issue by moloko** [oliverfoster/adapt-buildkit-rub#21]
The README is a bit lacking in some places. It would really help to have some more info on:
- the 'wait' option, when would this be useful?
- whether the various 'tracking' options require a moduleid (as is suggested in #19) or not
- when 'force', 'forceall', 'quick' and 'clean' should be used- and what exactly a 'resync' is
- more detail about what you can do with rubconfig.json
  Finally, I don't think the 'zip' command actually does create a zip file (if it does, I can't find the output!) - if not this should be removed/marked as something for future development

**Comment by oliverfoster** [comment]
zips will be on your desktop

**Comment by moloko** [comment]
oh yeah!! Well, there's another bit of info that needs adding then ;-)

**Comment by oliverfoster** [comment]
any good? > https://github.com/cgkineo/adapt-buildkit-rub/blob/develop/README.md

good as of rub-develop 0.1.4

**Comment by oliverfoster** [comment]
closing in anticipation of the next release
