### ISSUE TITLE
index.html from contrib-spoor's required folder not getting copied to build

### ISSUE THREAD

**Issue by moloko** [oliverfoster/adapt-buildkit-rub#22]
If you use the project structure where all your JSON and assets are stored only in the `builds` folder, rub doesn't copy in the index.html from contrib-spoor's `required` folder, the one in `src` is always used instead

This works fine if you use the standard Adapt Learning single course structure.

I haven't tested it with the older style of Kineo structure (where all the content is stored in `src/courses`)

**Comment by oliverfoster** [comment]
please test using develop branch as per [instructions](https://github.com/cgkineo/adapt-buildkit-rub/issues/16#issuecomment-171721999)

**Comment by moloko** [comment]
hmm well a bit of an improvement. tested on ken15186 but using the -d or -b switches didn't seem to do anything so tried -f and -F - still nothing other than these seem to pause on the 'synching index.html' for longer...

However, if I manually copy over the version of index.html from spoor's required folder, running `$ rub -f` doesn't cause it to be reverted to the standard index.html, like it did before... so that's an improvement of sorts!

**Comment by oliverfoster** [comment]
have plumbed in the -f and -F commands to make sure the overwrite happens, you'll need to rerun `adapt-buildkit install rub-develop` to try the latest changes

good as of rub-develop 0.1.4

(i think the pause is just it redoing the javascript. it'll batch run tasks 10 at a time, so it's probably coincidence that it hangs at the synching index line)

**Comment by moloko** [comment]
yep, that works for me

agree about the pause being it doing the javascript
