### ISSUE TITLE
json>txt files

### ISSUE THREAD

**Issue by oliverfoster** [oliverfoster/adapt-buildkit-rub#24]
https://github.com/cgkineo/adapt-buildkit-rub/tree/develop#file-extensions <

**Comment by oliverfoster** [comment]
@moloko ^ can you also do this one? i've tested this, it seems fine.

**Comment by moloko** [comment]
![2016-01-15 11_52_47-greenshot capture form](https://cloud.githubusercontent.com/assets/1249597/12352514/8ca95634-bb7e-11e5-8db2-c930e1f8c6bd.png)
I was using the Adapt OS-style project structure

**Comment by oliverfoster** [comment]
it's probably because the "buildkit-config.json.txt" needs the ".txt" removing. I'll change it to ".example" and update the readme.

I also need to make the tracking stuff multi-module, so i'll put a nice pretty error message in there instead of that ghastly thing.

**Comment by oliverfoster** [comment]
done, as of rub-develop 0.1.4

**Comment by moloko** [comment]
yep, working once I figured out the buildkit-config.json - the use of  `"example": {` in there was a bit confusing at first

**Comment by oliverfoster** [comment]
What would you suggest instead? Basic defaults I guess might be a better idea.

**Comment by moloko** [comment]
yeah I think that would be fine, I think it's less confusing to remove stuff you don't want in there

or switch to XML for the config and then you can just comment bits out HTML-style ;-)

**Comment by oliverfoster** [comment]
XML?! _melts slowly_

**Comment by moloko** [comment]
nothing wrong with XML! perfectly good for some situations. such as when you need to be able to comment stuff out easily, for one! also easy to differentiate between config and content... node attrs = config; node values = content

**Comment by oliverfoster** [comment]
added standard defaults, removed confusing bits.

**Comment by moloko** [comment]
+1
