### ISSUE TITLE
excessive cpu usage on watch

### ISSUE THREAD

**Issue by oliverfoster** [oliverfoster/adapt-buildkit-rub#25]
reduced, please confirm @chris-steele  please test using develop branch as per [instructions](https://github.com/cgkineo/adapt-buildkit-rub/issues/16#issuecomment-171721999)

good as of rub-develop 0.1.4

**Comment by samumist** [comment]
node consumes around 10-15% cpu with `./rub -s`.

Mac OSX 10.11.2
Chrome
Node version: 4.2.2

**Comment by oliverfoster** [comment]
closing before next release as new issues likely and this is confirmed better
