### ISSUE TITLE
Course not working after build with framework 2.0.7

### ISSUE THREAD

**Issue by jpablo128** [oliverfoster/adapt-buildkit-rub#26]
I'm trying to use adapt-buildkit-rub with the recently-released version 2.0.7 of the framework. The build seems to work fine, and the ./rub -s server process is fine, but when loading the course, lots of errors come up and the course doesn't work. I'm attaching screenshots of what I see in Chrome developer tools, so you can see the errors.
It seems to me that it might just be an issue with a path somewhere, because it seems that require.js is looking for things in the wrong place... but I really have no idea.

Some other observations, in case they help:
- This error condition happens both using Kineo's style directory structure, and also Adapt Learning structure
- If (using Adapt Learning structure) I build with "grunt build", the course works without any problems
- I've tried rub-develop, and I get the same error
- With version 2.0.6 of the framework, there's no error. Everything works fine.

![rub_errors1](https://cloud.githubusercontent.com/assets/1368489/13216069/e8e1d220-d959-11e5-8894-83500c715ea8.png)
![rub_errors_detail](https://cloud.githubusercontent.com/assets/1368489/13216070/e8e41710-d959-11e5-9d86-50cc677bdac1.png)

The complete log of errors from Chrome dev tools is:
`GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/adapt.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/models/configModel.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/drawer.js 404 (Not Found)
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/views/navigationView.js 404 (Not Found)
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/router.js 404 (Not Found)
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/popupManager.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/models/courseModel.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/accessibility.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/offlineStorage.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/models/contentObjectModel.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/models/questionModel.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/models/articleModel.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/models/componentModel.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/notify.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/adaptCollection.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/models/blockModel.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/device.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/models/lockingModel.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/views/articleView.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/models/adaptModel.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/views/menuView.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/views/questionView.js⋅
GET http://127.0.0.1:3001/adapt_sample/adapt/js/core/js/views/componentView.js⋅
`

I hope this information helps you. Thanks!

**Comment by oliverfoster** [comment]
Yup, I was hoping that wasn't going g to happen. I'll try fix it today. My fault. Sorry.

**Comment by oliverfoster** [comment]
can you test the next version?

**Comment by jpablo128** [comment]
Yes of course, testing now...

**Comment by jpablo128** [comment]
Thanks  @oliverfoster , it does work now! (rub version 0.0.57)

I did have to re-install adapt-buildkits ( sudo npm install -g adapt-buildkits ) ... I don't know if that was due to some kind of hiccup on my setup... but anyway, rub is working for me with framework  2.0.7

Thank you.

**Comment by oliverfoster** [comment]
beautiful, thanks for testing :)
