### ISSUE TITLE
Force building courses from 'builds/' directory while there's course in the 'src' directory

### ISSUE THREAD

**Issue by samumist** [oliverfoster/adapt-buildkit-rub#31]
This is more of a feature request rather than an issue.

I'm building courses with the latest `adapt_framework` (v2.0.9) and `rub-develop` and I'm having courses in both the `project_root/src` and `project_root/builds` directory.

when I run `rub -q`, only the course in the `project_root/src` got build, but not the courses in the `project_root/builds` directory.

I tried command like `rub -q c101`, it still only build the course in the `project_root/src` directory.

If I remove the course in the src/ directory, then `rub -q c101` builds as expected.

I'm wondering if there's a way to force build the courses in the `builds` directory while there is course in the `project_root/src` directory.

**Comment by moloko** [comment]
I suppose it should be possible but I don't get why you need some courses in `builds` and one course in `src/courses`? 
Wouldn't the solution simply be to remove the one in `src/courses` (so that it only exists in `builds`), thereby making everything consistent?

**Comment by samumist** [comment]
Thanks for the reply, Matt.

I install the adapt framework and plugins directly from the github repos, rather than from the cli, in order to keep them always on the latest version and be able to switch to different branch when required.  I like to keep the `src/courses` intact then I can easily track the change and use it as a `standard` course to test for  features.

Currently I'm having a local branch of the framework and having the `src/course` removed for the local branch to the `builds` directory to build all my course from the `builds` directory.

It'd be great if there's an option to force build. It's not a problem if it's not worth the effort since it's such an individual feature request.

**Comment by moloko** [comment]
ah OK that does make sense now, I can see why that would be useful.

I'll leave it up to @oliverfoster to decide whether to do this or not...

**Comment by oliverfoster** [comment]
added `--style` terminal option

**Comment by oliverfoster** [comment]
published - please test

**Comment by samumist** [comment]
All build `styles` worked as described.
The `default` option, without `--style` option, is actually option `0`, builds from `src/course`. Thought it would build all courses, i.e. build from `0+1+2`, guess I was wrong:-)

`rub -c --style number` worked as expected.

Great job!

The slight difference of course structure from different build location might be worth pointing out in the readme file.

From `src/course`:

```
config.json
en/
```

From `src/courses`

```
p101/
    config.json
    en/
p102/
    config.json
    en/
```

From `builds`

```
builds
├── p101
│   └── course
│       ├── config.json
│       └── zh-cn
└── p102
    └── course
        ├── config.json
        └── en
```

**Comment by oliverfoster** [comment]
Lol, I'm afraid the 0+1+2 would have been cool but this is as near as I could get in a short space of time.

I'll stick that diagram up on the readme when I get to my desk. Cheers dude. :D

**Comment by samumist** [comment]
Many thanks, Ollie. 
Issue closed.

**Comment by oliverfoster** [comment]
Diagram is up on rub develop branch :D
