### ISSUE TITLE
global exclusion for folderexclusions doesn't work.

### ISSUE THREAD

**Issue by samumist** [oliverfoster/adapt-buildkit-rub#32]
I have the following code in the `buildkit-config.json` to exclude globally some menus, but the doesn't seem to work. The menus still get build when I run `rub -ds`.

Folderexclusions within the course option works as expected.

``` json
{
    "folderexclusions": {
        "course": {
            "c101": [
                ""
            ],
            "quiz": [
                ""
            ],
            "samplecourse": [
                ""
            ]
        },
        "global": [
            "adapt-hotspot-menu",
            "adapt-cover-menu"
        ]
    },
```

**Build Environment**
- Latest Adapt-framework
- rub-develop latest version

**Comment by oliverfoster** [comment]
yup, the config is either or at the moment. will fix

**Comment by oliverfoster** [comment]
done on rub-develop

**Comment by oliverfoster** [comment]
published - please test

**Comment by samumist** [comment]
Tested. The `global exclusion` worked as expected. 
Great job!
