### ISSUE TITLE
CPU usage (relatively) high

### ISSUE THREAD

**Issue by chris-steele** [oliverfoster/adapt-buildkit-rub#4]
rub watch consumes about 20-25% of my CPU (i5-4278U). It is the node process of course, so may be outside of our control, but it seems woefully excessive. I don't recall grunt/gulp watch using this kind of power.

**Comment by oliverfoster** [comment]
Yea, that'll be the watch loop being too keen (checks every 100 milliseconds at the moment, doh). Windows or Mac?

Multiple course folders?

**Comment by oliverfoster** [comment]
I've bumped it down to check once a second. Although that is probably a bit too often also.

**Comment by chris-steele** [comment]
Thanks for doing this I'll take a look shortly. Yeah it was single course and on Windows.

**Comment by samumist** [comment]
It's much better now, about 35-40% CPU. Used to be 100% CPU a few days ago when running `./rub -s`

Single course, Mac i7 2.3 GHz.

**Comment by oliverfoster** [comment]
pr #10 further lowers this to 2 seconds rather than 1 or 0.1
