### ISSUE TITLE
rub to populate imsmanifest

### ISSUE THREAD

**Issue by joe-replin** [oliverfoster/adapt-buildkit-rub#44]
Hello, I was wondering if it was possible for rub to adjust the @@course.title & @@course.description variables to populate the imsmanifest.xml file. 

I've discovered I could substitute handlebar variables instead but was wondering if the above was possible.

**Comment by oliverfoster** [comment]
Cool. I'll look into it, but it won't be before the end of February. I'll see what I can do. I've got multi-language stuffs to do as well.

**Comment by joe-replin** [comment]
Thank you Ollie for the quick response. I wouldn't have any immediate need for this. This was just a "nice-to-have" thought really.

**Comment by joe-replin** [comment]
This has long been completed.
